// <auto-generated />
using System;
using MAUIBLAZORHYBRID.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAUIBLAZORHYBRID.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250731060437_tablenamefix")]
    partial class tablenamefix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.BillItem", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("categorycatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("itemType")
                        .HasColumnType("INTEGER");

                    b.HasKey("itemId");

                    b.HasIndex("categorycatId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.BillItemUnit", b =>
                {
                    b.Property<int>("itemUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("itemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("unitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("itemUnitId");

                    b.HasIndex("itemId");

                    b.HasIndex("unitId");

                    b.ToTable("BillItemUnits");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.BillStation", b =>
                {
                    b.Property<int>("billStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("billStationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("branchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("billStationId");

                    b.HasIndex("branchId");

                    b.ToTable("BillStations");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.BranchMaster", b =>
                {
                    b.Property<int>("branchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("branchName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("branchId");

                    b.ToTable("BranchMasters");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.Category", b =>
                {
                    b.Property<int>("catId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("catName")
                        .HasColumnType("TEXT");

                    b.Property<int>("catType")
                        .HasColumnType("INTEGER");

                    b.HasKey("catId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.DiningSpace", b =>
                {
                    b.Property<int>("diningSpaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("diningSpaceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("diningSpaceId");

                    b.ToTable("DiningSpaces");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.DiningSpaceItemRate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("diningSpaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("itemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("itemRate")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("diningSpaceId");

                    b.HasIndex("itemId");

                    b.ToTable("DiningSpaceItemRates");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.Item", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MainItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("itemRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("picURL")
                        .HasColumnType("TEXT");

                    b.Property<int>("subCatId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("unitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("itemId");

                    b.HasIndex("MainItemId");

                    b.HasIndex("subCatId");

                    b.HasIndex("unitId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.MainItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MainItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MainItems");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.SubCategory", b =>
                {
                    b.Property<int>("subCatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("catId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("subCatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("subCatId");

                    b.HasIndex("catId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.Table", b =>
                {
                    b.Property<int>("tableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("tableId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.TableDiningSpace", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("branchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("diningspaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TablesDiningSpaces");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.Unit", b =>
                {
                    b.Property<int>("unitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("unitName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("unitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.VWItemParentChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("categorycatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("childItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("childItemcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("childItemname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("itemtype")
                        .HasColumnType("INTEGER");

                    b.Property<int>("parentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("parentItemcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("parentItemname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("unitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("categorycatId");

                    b.HasIndex("unitId");

                    b.ToTable("ItemParentChilds");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.BillItem", b =>
                {
                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.Category", "category")
                        .WithMany()
                        .HasForeignKey("categorycatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.BillItemUnit", b =>
                {
                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.BillItem", "Item")
                        .WithMany("ItemUnits")
                        .HasForeignKey("itemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("unitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.BillStation", b =>
                {
                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.BranchMaster", "Branch")
                        .WithMany("BillStations")
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.DiningSpaceItemRate", b =>
                {
                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.DiningSpace", "diningSpace")
                        .WithMany()
                        .HasForeignKey("diningSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.BillItem", "item")
                        .WithMany("DiningSpaceItemRates")
                        .HasForeignKey("itemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("diningSpace");

                    b.Navigation("item");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.Item", b =>
                {
                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.MainItem", "MainItem")
                        .WithMany("Items")
                        .HasForeignKey("MainItemId");

                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.SubCategory", "SubCategory")
                        .WithMany("Items")
                        .HasForeignKey("subCatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("unitId");

                    b.Navigation("MainItem");

                    b.Navigation("SubCategory");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.SubCategory", b =>
                {
                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("catId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.VWItemParentChild", b =>
                {
                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.Category", "category")
                        .WithMany()
                        .HasForeignKey("categorycatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("unitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("category");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.BillItem", b =>
                {
                    b.Navigation("DiningSpaceItemRates");

                    b.Navigation("ItemUnits");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.BranchMaster", b =>
                {
                    b.Navigation("BillStations");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.MainItem", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.SubCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
