// <auto-generated />
using MAUIBLAZORHYBRID.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MAUIBLAZORHYBRID.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250617014800_categorysubcatmanytoone")]
    partial class categorysubcatmanytoone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.Category", b =>
                {
                    b.Property<int>("catId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("catName")
                        .HasColumnType("TEXT");

                    b.Property<int>("catType")
                        .HasColumnType("INTEGER");

                    b.HasKey("catId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.Item", b =>
                {
                    b.Property<int>("itemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCategorysubCatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("picURL")
                        .HasColumnType("TEXT");

                    b.Property<int>("subCatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("itemId");

                    b.HasIndex("SubCategorysubCatId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.SubCategory", b =>
                {
                    b.Property<int>("subCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorycatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("catId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("subCatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("subCatId");

                    b.HasIndex("CategorycatId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.Item", b =>
                {
                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.SubCategory", "SubCategory")
                        .WithMany("Items")
                        .HasForeignKey("SubCategorysubCatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.SubCategory", b =>
                {
                    b.HasOne("MAUIBLAZORHYBRID.Data.Data.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategorycatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("MAUIBLAZORHYBRID.Data.Data.SubCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
